# Generated by Django 3.2.3 on 2021-06-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board_api', '0001_initial'),
        ('column_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('status', models.BooleanField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_api.board')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='column_api.lanes')),
            ],
        ),
    ]
