# Generated by Django 3.2.3 on 2021-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.SmallIntegerField()),
                ('column_id', models.SmallIntegerField()),
                ('capacity', models.SmallIntegerField(default=20)),
                ('limit', models.SmallIntegerField(default=5)),
            ],
        ),
    ]
