# Generated by Django 3.2.3 on 2021-06-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
