# Generated by Django 3.2.3 on 2021-06-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardID', models.SmallIntegerField()),
                ('columnID', models.SmallIntegerField()),
                ('capacity', models.SmallIntegerField()),
                ('limit', models.SmallIntegerField()),
            ],
        ),
    ]
